

export type BRI_DEVELOPMENT = "DEVELOPMENT";
export type BRI_PRODUCTION = "PRODUCTION";

export const BRI_DEVELOPMENT : BRI_DEVELOPMENT = "DEVELOPMENT";
export const BRI_PRODUCTION : BRI_PRODUCTION = "PRODUCTION";