

export type ARDUINO_TYPE_SERIAL = "ARDUINO_TYPE_SERIAL";
export type ARDUINO_TYPE_WIFI = "ARDUINO_TYPE_WIFI";

export const ARDUINO_TYPE_WIFI : ARDUINO_TYPE_WIFI = "ARDUINO_TYPE_WIFI";
export const ARDUINO_TYPE_SERIAL : ARDUINO_TYPE_SERIAL = "ARDUINO_TYPE_SERIAL";

export type ArduinoTypes = ARDUINO_TYPE_SERIAL | ARDUINO_TYPE_WIFI;