

export type ESCPOS_USB = "ESCPOS_USB";
export type ESCPOS_NETWORK = "ESCPOS_NETWORK";

export const TYPE_ESCPOS_USB : ESCPOS_USB = "ESCPOS_USB";
export const TYPE_ESCPOS_NETWORK : ESCPOS_NETWORK = "ESCPOS_NETWORK";