

export type TYPE_ESCPOS_USB = "ESCPOS_USB";
export type TYPE_ESCPOS_NETWORK = "ESCPOS_NETWORK";

export type TYPE_DEVELOPMENT = "DEVELOPMENT";
export type TYPE_PRODUCTION = "PRODUCTION";

export type TYPE_ALL_STATES = TYPE_PRODUCTION | TYPE_DEVELOPMENT;

export const DEVELOPMENT : TYPE_DEVELOPMENT = "DEVELOPMENT";
export const PRODUCTION : TYPE_PRODUCTION = "PRODUCTION";


export const ESCPOS_USB : TYPE_ESCPOS_USB = "ESCPOS_USB";
export const ESCPOS_NETWORK : TYPE_ESCPOS_NETWORK = "ESCPOS_NETWORK";